### PR TITLE
Fix camera button not working on Keysend Experiment

### PR DESCRIPTION
**Pull request by niteshbalusu11**
Fix experimental keysend camera screen.

### CODE REVIEW

**Comment by niteshbalusu11** [comment]
ah shit, my SortImport plugin sorted all imports in alphabetical order. if it's an issue let me know i can submit a fresh PR.

**Comment by niteshbalusu11** [comment]
> ah shit, my SortImport plugin sorted all imports in alphabetical order. if it's an issue let me know i can submit a fresh PR.

Nvm - fixed it.

**Comment by niteshbalusu11** [comment]
https://github.com/hsjoberg/blixt-wallet/issues/1074

**Comment by hsjoberg** [comment]
LGTM! 💯

**Pull request merged**
