### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Comment by rex4539** [comment]
@hsjoberg Could you take a look?

**Comment by hsjoberg** [comment]
Hi, sure. Nice fixes, thank you.
Can you please not change the files in `proto/` as they're coming from https://github.com/lightningnetwork/lnd and would revert back to the typos when I update the proto files.

**Comment by rex4539** [comment]
Reverted those changes.

**Comment by hsjoberg** [comment]
Thank you. 🙏

**Pull request merged**
